apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-hub

resources:
  - namespace.yaml
  - gateway-config.yaml
  - gateway-deployment.yaml
  - gateway-hpa.yaml
  - gateway-pdb.yaml
  - ingress.yaml
  - cert-manager/cluster-issuer.yaml
  - cert-manager/gateway-cert.yaml
  - cert-manager/client-ca-secret.yaml

commonLabels:
  app.kubernetes.io/part-of: federated-observability
  app.kubernetes.io/managed-by: kustomize
