apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus/rbac.yaml
  - prometheus/config.yaml
  - prometheus/deployment.yaml
  - loki/config.yaml
  - loki/statefulset.yaml
  - tempo/config.yaml
  - tempo/statefulset.yaml
  - grafana/config.yaml
  - grafana/dashboard-providers.yaml
  - grafana/dashboards-configmap.yaml
  - grafana/deployment.yaml
  - grafana/ingress.yaml
  - dcgm-exporter.yaml
