apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-hub

resources:
  - namespace.yaml
  - config.yaml
  - deployment.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
  - cert-manager/cluster-issuer.yaml
  - cert-manager/gateway-cert.yaml
  # client-ca secret is managed by VSO (hub/vault-secrets-operator/)

commonLabels:
  app.kubernetes.io/part-of: federated-observability
  app.kubernetes.io/managed-by: kustomize
