apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - agent-config.yaml
  - agent-daemonset.yaml
  - aggregator-config.yaml
  - aggregator-deployment.yaml
  - aggregator-hpa.yaml
  - aggregator-pdb.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/part-of: federated-observability
  app.kubernetes.io/managed-by: kustomize
