apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - agent/rbac.yaml
  - agent/config.yaml
  - agent/daemonset.yaml
  - scraper/rbac.yaml
  - scraper/config.yaml
  - scraper/deployment.yaml
  - kube-state-metrics.yaml
