apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-hub

resources:
  - namespace.yaml
  - redpanda-config.yaml
  - redpanda-statefulset.yaml
  - redpanda-service.yaml
  - topics.yaml

commonLabels:
  app.kubernetes.io/part-of: federated-observability
  app.kubernetes.io/managed-by: kustomize
