apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: observability-hub
  labels:
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/part-of: federated-observability
spec:
  selector:
    app.kubernetes.io/name: victoria-metrics
  ports:
    - name: http
      port: 8428
      targetPort: http
      protocol: TCP
