apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-hub

resources:
  - namespace.yaml
  - router-splunk/config.yaml
  - router-splunk/deployment.yaml
  - router-splunk/secret.yaml
  - router-datadog/config.yaml
  - router-datadog/deployment.yaml
  - router-datadog/secret.yaml
  - router-otlp/config.yaml
  - router-otlp/deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: federated-observability
  app.kubernetes.io/managed-by: kustomize
